---
- hosts: localhost
  connection: local
  tasks: 
    - docker_container:
        name: myhello
        image: kjhak0416/myhello:latest
        state: started
        ports: 
          - "80:8080"
...
